### ISSUE TITLE
Adding translators credits

### ISSUE THREAD

**Issue by pietroppeter** [harisont/covid-19#11]
From updated README.md:

> Feel free to add yourself in the header/footer credits as a translator! :)

How do we want to proceed on that? I would say we could everyone who contributed in the footer (in the header it makes sense if there is a single translator, I guess, cfr [Japanese translation](https://eed3si9n.github.io/covid-19/)).

Last line of footer says:

> Qualunque altro errore è probabilmente colpa di Nicky.

We could add to that:

> Mmh, forse no, la maggior parte degli errori sono probabilmente colpa dei traduttori! 😜
>
> Traduzione in italiano di: *i nostri nomi*

As for our names, mine is "Pietro Peterlongo", I will let you add yours here (yeah, I kind of can guess them but...). Also feel free to suggest other wordings to credit the translation!

**Comment by simonefalcini** [comment]
Ahah for me it's ok to add what you said. Mine is Simone Falcini :)

**Comment by mendaomn** [comment]
Sounds great! My name is Alessandro Menduni ;)

**Comment by harisont** [comment]
Nice, please do that!
My name is Arianna Masciolini.

**Comment by pietroppeter** [comment]
added commit that closes this in #12. Order is alphabetic by first name as in list of names right before this.
