### ISSUE TITLE
the referenced thumbnail image is in English 

### ISSUE THREAD

**Issue by grgfgh** [harisont/covid-19#15]
when trying to share the Italian translation website Facebook and whatsapp, the thumbnail shows the English version, I believe it can be fixed by changing this part of the index header
`<meta property="og:image" content="https://ncase.me/covid-19/sharing/thumbnail.png"> `
to
`<meta property="og:image" content="https://harisont.github.io/covid-19/sharing/thumbnail.png">`

**Comment by pietroppeter** [comment]
Yes you are right, as I mentioned in the other issue feel free to try a PR otherwise we will take care. Thanks and welcome here, any help is appreciated!

**Comment by pietroppeter** [comment]
Should be closed by #12 when merged
