### ISSUE TITLE
Translating technical footnote

### ISSUE THREAD

**Issue by harisont** [harisont/covid-19#16]
I was not able to translate this footnote as I don't really know much about the domain.

> [^outgoing]: “The overall 3.4 fold reduction [70% reduction] in aerosol copy numbers we observed combined with a nearly complete elimination of large droplet spray demonstrated by Johnson et al. suggests that surgical masks worn by infected persons could have a clinically significant impact on transmission.” [Milton DK, Fabian MP, Cowling BJ, Grantham ML, McDevitt JJ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3591312/)

**Comment by pietroppeter** [comment]
closed by #12
