### ISSUE TITLE
automate words.md to index.html without splitting index.html

### ISSUE THREAD

**Issue by jkoelling** [harisont/covid-19#17]
Hey there,

we adopted your idea of having a script for the build step and improved on it by making the split unnecessary and having an automated build process in github that happens whenever someone pushes to master (for this github actions/workflows need to be enabled in the repo).

I've opened a PR on Nicky's original repo, I hope it will be useful to you too even if your are almost done already. :)

Let's hope that lots of people will read this and learn from it! :)

Best,
Jan

https://github.com/ncase/covid-19/pull/54

**Comment by harisont** [comment]
Great! Thanks. And yes, let's hope many people play with this article...
