### ISSUE TITLE
Markup issue

### ISSUE THREAD

**Issue by simonefalcini** [harisont/covid-19#19]
I think there is a markup issue in the index.html at 29:

https://github.com/harisont/covid-19/blob/e3e9cf6bf828a9e647ed57d8be050f146c3769fb/index.html#L466

See screenshot:

![Screen Shot 2020-05-22 at 12 26 55](https://user-images.githubusercontent.com/1196854/82658653-aee32200-9c27-11ea-849e-b982fcd44843.png)

**Comment by pietroppeter** [comment]
you are right, thanks for noticing! let me see if I can fix it.

**Comment by pietroppeter** [comment]
ok, fixed!
