### ISSUE TITLE
Activate github pages

### ISSUE THREAD

**Issue by pietroppeter** [harisont/covid-19#5]
This has to be done at some point.
Go to 'Settings' of your repository page and choose your master branch as your source.

Example:

![image](https://user-images.githubusercontent.com/4997234/80929334-5dbfdb00-8dab-11ea-990b-4d9f55f24654.png)

**Comment by harisont** [comment]
Yes, I'll do that later today. Don't worry I used pages multiple times ;)

**Comment by harisont** [comment]
Pages active!
